### ISSUE TITLE
Reviews Plugin - "Product.reviewRating" is not supported by "postgres" database

### ISSUE THREAD

**Issue by rrubio** [vendure-ecommerce/real-world-vendure#1]
Using PostgreSQL with populated demo data.

Without "reviews" plugin, app starts fine and able to access admin panel and api's.

With reviews plugin installed and on "yarn start" the following error occurs:

`[run:server] error 26/11/19, 00:13 - [TypeOrmModule] Unable to connect to the database. Retrying (9)...
[run:server] DataTypeNotSupportedError: Data type "double" in "Product.reviewRating" is not supported by "postgres" database.`

Expected behavior using TypeORM is for backward compatibility.

NOTE: using the default SQLite demo version, all is ok.

BTW - Thank you for putting this demo together.

**Comment by michaelbromley** [comment]
Hi, thanks for the report. 

This actually looks to be a bug in core. I'll create an issue there.

**Comment by rrubio** [comment]
Awesome! thank you man!
