### ISSUE TITLE
Latest version not working as SQLite3 reference is broken.

### ISSUE THREAD

**Issue by rlodhiya2502** [vendure-ecommerce/real-world-vendure#10]
Currently, I am trying to follow as instructed in the readme file. 

I got the latest copy of the git repo.

In the terminal, I typed yarn and entered. 

And I got this error 
real-world-vendure/node_modules/sqlite3: Command failed.
Exit code: 1

I checked with sqlite3, and it has an issue. Tested with macOS and Windows 10. Both reflect the same issues.

**Comment by michaelbromley** [comment]
Hi,

is there any more output with the error? 

> I checked with sqlite3, and it has an issue.

Do you mean there is a known issue with sqlite3? If so, can you link to it?

**Comment by rlodhiya2502** [comment]
To correct the error you need to remove sqlite3 latest (5.0.1) version. (Use following command)

npm uninstall sqlite3

and reinstall version 5.0.0

npm install --save sqlite3@5.0.0

you might need to fix vulnerabilities using the following command afterwards

npm audit fix --force

Still investigating further. 

========================================

To replicate the error, I have done the following - 

1. npm install --save sqlite3@latest 
And it should generate detail logs.

Please check this link as it suggests that build failing [https://www.npmjs.com/package/sqlite3](https://www.npmjs.com/package/sqlite3)

Now, better-sqlite3 is also affected as well. 

Preliminary investigation suggests that yarn.lock file is out-of-sync and might need to rebuild from the package.json.

**Comment by michaelbromley** [comment]
Thanks for the extra detail.

> To correct the error you need to remove sqlite3 latest (5.0.1) version.

The version in package.json is pinned to 4.1.0 (https://github.com/vendure-ecommerce/real-world-vendure/blob/master/package.json#L26), so I'm not sure how you got v5.0.1 installed when running `yarn`.

**Comment by rlodhiya2502** [comment]
Thank you for your inputs.

sqlite3@4.1.0 also has issues. 

I have created an empty project and run the following command.

npm install --save sqlite3@4.1.0 

and here it's log 
rlodhiya@Ravis-MBP vendure-test % npm install --save sqlite3@4.1.0
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@14.15.1 | darwin | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-darwin-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-darwin-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-darwin-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.1.0 and node@14.15.1 (node-v83 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.1.0/node-v83-darwin-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.1 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.1 | darwin | x64
npm ERR! gyp info find Python using Python version 2.7.16 found at "/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python"
npm ERR! gyp info spawn /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/rlodhiya/Library/Caches/node-gyp/14.15.1/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/rlodhiya/Library/Caches/node-gyp/14.15.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/rlodhiya/Library/Caches/node-gyp/14.15.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
npm ERR! 
npm ERR! No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
npm ERR! 
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@14.15.1 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Darwin 20.3.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v83"
npm ERR! gyp ERR! cwd /Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3
npm ERR! gyp ERR! node -v v14.15.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3/lib/binding/node-v83-darwin-x64 --napi_version=7 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v83' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! node-pre-gyp ERR! System Darwin 20.3.0
npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Volumes/Macintosh HD - Data/Projects/vendure-test/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v14.15.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/rlodhiya/.npm/_logs/2021-02-08T19_14_02_486Z-debug.log
-----------------------------------------------------------

I am not sure what to do with the error. 

But keep you posted.

**Comment by Draykee** [comment]
This wouldn't solve the issue itself, but maybe the repository should change to better-sqlite3 as the default.
I also had this problem with multiple team members.

**Comment by michaelbromley** [comment]
Yes, I moved to better-sqlite3 for new Vendure projects, and this should be updated too. Would you like to PR for this?
