### ISSUE TITLE
ProductReview exposes Customer to the public API

### ISSUE THREAD

**Issue by Draykee** [vendure-ecommerce/real-world-vendure#30]
https://github.com/vendure-ecommerce/real-world-vendure/blob/80ff68c195990edc0342bdb1fbfcef2e5437fdb0/src/plugins/reviews/graphql/api-extensions.ts#L13

Everyone could see the orders of a customer via ` product -> reviews -> customer`. I think this should be restricted.

**Comment by michaelbromley** [comment]
Yes, good point. There should be an Allow decorator on the entity resolver, or maybe a different type for the public API.
